/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SubmissionId = IDL.Nat;
export const ServiceType = IDL.Variant({
  'handsOnAssistance' : IDL.Null,
  'carpetAndFloorCare' : IDL.Null,
  'tileAndGroutClean' : IDL.Null,
  'endOfLease' : IDL.Null,
  'externalCleaning' : IDL.Null,
  'furnitureAndMattressClean' : IDL.Null,
  'pressureCleaning' : IDL.Null,
  'internalCleaning' : IDL.Null,
});
export const Time = IDL.Int;
export const Submission = IDL.Record({
  'id' : SubmissionId,
  'serviceType' : ServiceType,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'address' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'addAdminPrincipal' : IDL.Func([IDL.Principal], [], []),
  'getAllFormSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'getFormSubmission' : IDL.Func([SubmissionId], [Submission], ['query']),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ServiceType, IDL.Text],
      [SubmissionId],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SubmissionId = IDL.Nat;
  const ServiceType = IDL.Variant({
    'handsOnAssistance' : IDL.Null,
    'carpetAndFloorCare' : IDL.Null,
    'tileAndGroutClean' : IDL.Null,
    'endOfLease' : IDL.Null,
    'externalCleaning' : IDL.Null,
    'furnitureAndMattressClean' : IDL.Null,
    'pressureCleaning' : IDL.Null,
    'internalCleaning' : IDL.Null,
  });
  const Time = IDL.Int;
  const Submission = IDL.Record({
    'id' : SubmissionId,
    'serviceType' : ServiceType,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'address' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'addAdminPrincipal' : IDL.Func([IDL.Principal], [], []),
    'getAllFormSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'getFormSubmission' : IDL.Func([SubmissionId], [Submission], ['query']),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ServiceType, IDL.Text],
        [SubmissionId],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };